name: Convert PowerShell to EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PS2EXE
      shell: powershell
      run: |
        Install-Module -Name ps2exe -RequiredVersion 1.0.14 -Force -Scope CurrentUser
      
    - name: Convert PowerShell script to EXE
      shell: powershell
      run: |
        ps2exe .\copyfiles.ps1 .\output\copyfiles.exe
