name: Convert PowerShell to EXE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: "Setup PowerShell Toolkit"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0"
    - run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Write-GitHubActionsNotice -Message 'Hello, world!'
      shell: "pwsh"
      
    - name: Install PS2EXE
      shell: "pwsh"
      run: |
        Install-Module -Name ps2exe -RequiredVersion 1.0.14 -Force -Scope 'Local'
      
    - name: Convert PowerShell script to EXE
      shell: "pwsh"
      run: |
        ps2exe .\copyfiles.ps1 .\output\copyfiles.exe
        Copy-Item -Path .\employee.xml -Destination .\output\

