name: Package PowerShell Script

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Install ps2exe module
      run: Install-Module -Name ps2exe -Force -Scope CurrentUser

    - name: Package PowerShell script
      run: |
        ps2exe .\copyfiles.ps1 .\output\copyfiles.exe
        # If you have additional files, you can copy them to the output directory
        Copy-Item -Path .\employee.xml -Destination .\output\

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: packaged-script
        path: .\output\copyfiles.exe
